# Generated by Django 5.1.1 on 2024-10-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_client_track'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client_Track',
        ),
    ]
