# Generated by Django 5.1.1 on 2024-10-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_delete_client_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='time',
            field=models.CharField(default='0:00', max_length=12),
        ),
    ]
