# Generated by Django 5.1.1 on 2024-10-04 02:35

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_login_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/TitanX/GDisk/Programming/PYServer/Evil_site/media/avatar')), upload_to=''),
        ),
    ]
