# Generated by Django 5.1.1 on 2024-10-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_client_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='musiclist',
        ),
    ]
